name: Build Image and Deploy to Lambda

on:
  push:
    branches: [master]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY_NAME: menma-portfolio
  DOMAIN_NAME: preview.menma.dev
  CLOUDFLARE_ZONE_ID: f6c90d0c7226fc41d698fdd12a660ddb

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ***REMOVED***
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR image URI
        id: ecr
        run: |
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:latest" >> $GITHUB_ENV

      - name: Retrieve required secrets from AWS Secrets Manager
        id: get_secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: arn:aws:secretsmanager:eu-central-1:401821118684:secret:***REMOVED***-KnKedI
          parse-json-secrets: true

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize and Deploy Terraform
        run: |
          cd terraform
          terraform init
          terraform apply \
            -var 'image_uri=$IMAGE_URI' \
            -var 'domain_name=${{ env.DOMAIN_NAME }}' \
            -var 'cloudflare_zone_id=${{ env.CLOUDFLARE_ZONE_ID }}' \
            -var 'cloudflare_api_key=${{ env.MENMAPORTFOLIOKEYS_CLOUDFLARE_API_KEY }}' \
            -auto-approve